# Generated by Django 6.0.6 on 2026-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="document",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="document",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="document",
            name="page_count",
            field=models.IntegerField(default=0),
        ),
    ]
